import Head from "next/head";
import type { NextPage } from "next";

//import NavBar from "../../components/NavBar";
import UsersDetail from "../../components/UsersDetail";

import React, { useState, useEffect } from "react";
import { useSelector, useDispatch } from "react-redux";
//import Link from "next/link";
//import { List, ListItemText } from "@mui/material";

import type { userDetail } from "../../types";
//import ShowDetail from "../views/ShowDetail"

const Detail: NextPage = () => {
  const user = useSelector(
    (state: { userDetail: userDetail }) => state.userDetail
  );
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <NavBar /> */}
      <main>
        <UsersDetail user={user} />
      </main>
      <footer>futer</footer>
    </div>
  );
};

export default Detail;
