import React, { useEffect } from "react";
import { useSelector, useDispatch } from "react-redux";
import Head from "next/head";
import { useRouter } from "next/router";
import type { NextPage } from "next";

import NavBar from "../../components/NavBar";
import UsersDetail from "../../components/UsersDetail";

//import Link from "next/link";
//import { List, ListItemText } from "@mui/material";
import { getUserDetail } from "../../store/slices/getUserDetail";

import type { userDetail } from "../../types";

const Detail: NextPage = () => {
  const dispatch = useDispatch();
  const router = useRouter();
  const user = useSelector(
    (state: { userDetail: userDetail }) => state.userDetail
  );

  useEffect(() => {
    dispatch(getUserDetail(router.query.userLogin as string));
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar /> 
      <main>
        <UsersDetail user={user} />
      </main>
      <footer>futer</footer>
    </div>
  );
};

export default Detail;
