import Head from "next/head";
import type { NextPage } from "next";

import NavBar from "../src/components/NavBar";
import UsersList from "../src/components/UsersList";
import UsersDetail from "../src/components/UsersDetail";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main>
        <UsersList />
      </main>
      <footer>futer</footer>
    </div>
  );
};

export default Home;
