import Head from "next/head";
import type { NextPage } from "next";

import NavBar from "../components/NavBar";
import Search from "../components/Search";
import UsersList from "../components/UsersList";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main>
        <Search />
        <UsersList />
      </main>
      <footer>futer</footer>
    </div>
  );
};

export default Home;
